version: "3"

services:
    arkweb:
        build: ./web
        container_name: arkweb
        ports:
            - "5000:5000"
        networks:
            - web-tier

    arkapi:
        build: ./api
        container_name: arkapi
        ports:
            - "5001:5001"
        networks: 
            - data-tier
            - service-tier
            - web-tier
        environment:
            - SQLALCHEMY_ENGINE_URI=postgresql://postgres@db
            - SQLALCHEMY_DATABASE=arkapi
            - SQLALCHEMY_MIGRATE_REPO=db_repository
            - SQLALCHEMY_TRACK_NOTIFICATIONS=true

    db:
        image: postgres:9.4
        container_name: db
        networks:
            - data-tier
        environment:
            - POSTGRES_USER=arkweb
            - POSTGRES_PASSWORD=arkweb

networks:
    web-tier:
    service-tier:
    data-tier:
